# Created 2023-05-23 ti. 14:09
#+title: Kubernetes at Home
#+author: Geir Okkenhaug Jerstad
#+export_file_name: README.org

* Operator - Orchestrator -

Hey, that's us. The human interacting with the system.

** NixOS k8s-tools

#+begin_src nix
  { config, pkgs, ... }:
  {
    environment.systemPackages = with pkgs; [
      kubectl
      k9s
      kubernetes-helm
      k3sup
    ];
  }
#+end_src

** emacs k8s
** git provider

* OS/kubernetes distro
the cluster is rather bare. It has one machine for k8s, one for storage and one for dns
** Talos
Talos serves a minimal k8s distribution on top of a minimal Linux base. api driven configuration with talosctl and yaml files.


#+begin_src shell

#+end_src

** Alpine/K3s

Alpine Linux is a minimal Linux distribution . It use Openrc and the apk package manager
It serves as a stable minimal base upon we can run the minimal k3s kubernetes distro.
Reducing the attack surface and leverage the apko/melange/wolfi chainguard container creation.


#+begin_src bash
  setup-alpine
#+end_src

* GitOps
** Flux
* VPN
wireguard - tail/headscale??xxxxxx
* External Loadbalancer/reverse-proxy
** metallb
* Ingress
** Traefik
* Certs
** Let's encrypt
* DNS
** externalDNS ??
* Storage
** nfs
** distributed storage ceph
* Security
** scanning - trivy
** integrity/identity - spiffe/spire
* Containers
** Wolfi os/apko/melange
** NixOS containers
** external containers
** sigstore chainguard
* Build CI/CD
** tekon/jenkinsX
